services:
  db:
    image: mysql:8.0
    container_name: crud_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_cicd
    volumes:
      - mysql_data:/var/lib/mysql


  backend:
    build: ./Backend
    container_name: crud_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/crud_cicd

  frontend:
    build: ./Frontend
    container_name: crud_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data:
